### ISSUE TITLE
Missing pstl dependency

### ISSUE THREAD

**Issue by seanbaxter** [cor3ntin/ext-unicode-db#6]
When I run `cmake ..`:
```
CMake Error at CMakeLists.txt:40 (add_subdirectory):
  add_subdirectory given source "third_party/pstl2019_20191006oss" which is
  not an existing directory.
```

I get the git submodules range-v3 and fmt. But I think pstl is missing.

**Comment by cor3ntin** [comment]
I completely missed this issue, but this should be fixed now, I'm using vcpk for the dependencies
